### ISSUE TITLE
Add Sails and Sequelize to peerDependencies

### ISSUE THREAD

**Issue by joshrickert** [KSDaemon/sails-hook-sequelize#19]
Given that this is a "glue" plugin between Sails and Sequelize, it seems like it pretty-well fits the [use case](https://nodejs.org/en/blog/npm/peer-dependencies/) for adding those as peer dependencies.

**Comment by KSDaemon** [comment]
Hi @joshrickert! Well... Sequelize is listed in `dependencies` because this hook will not work without it :)
As for sails — it may be interesting idea, but i think there are some points here: we need to specify peer dependency version. Right now hook supports both v0.12 and v1.0 sails versions. Because npm uses semver, and only one version can be specified, all we can make is to define v0.12 or v1.0 sails version. But that can mislead some developers. So i think we can just ignore it for now :)

**Comment by joshrickert** [comment]
Appreciate the response! I think the reason I originally opened this was that the module was installing its own, slightly older, version of the libraries mentioned. With the de-duplication features present in the latest versions of npm and yarn, it seems to be less of an issue. It may still be wise to make sure your version requirements are as broad as is practical. Thanks for sharing this plugin with the community, by the way, it's been incredibly helpful.

**Comment by KSDaemon** [comment]
Glad to hear! :)
